const router = require("express").Router();
const { protect, requireActiveSubscription } = require("../middleware/auth");
const { listTests, startTest, saveResponse, submitTest, getAnalysis } = require("../controllers/mockController");
router.use(protect);
router.use(requireActiveSubscription);
router.get("/", listTests);
router.post("/:testId/start", startTest);
router.post("/:attemptId/response", saveResponse);
router.post("/:attemptId/submit", submitTest);
router.get("/:attemptId/analysis", getAnalysis);
module.exports = router;
