const router = require("express").Router();
const { protect, requireActiveSubscription } = require("../middleware/auth");
const { getQuestions, getChapters, getStats, getRecommended, markSolved, getPyqYears } = require("../controllers/practiceController");
router.use(protect);
router.use(requireActiveSubscription);
router.get("/questions", getQuestions);
router.get("/pyq-years", getPyqYears);
router.get("/chapters", getChapters);
router.get("/stats", getStats);
router.get("/recommended", getRecommended);
router.post("/solve", markSolved);
module.exports = router;
